### PR TITLE
Add instructions for updating Nginx configuration

### PR DESCRIPTION
**Pull request by ssoloff**
These instructions will replace the [corresponding wiki page](https://github.com/triplea-game/tripleawarclub.org/wiki/Update-Nginx-configuration).

### CODE REVIEW

**Review by RoiEXLab — APPROVED** [review]
One could argue that since there's only one file left, you could simply download the raw file using wget or curl, what's what I was doing to directly overwrite the file using the `-O` flag

**Comment by ssoloff** [comment]
@RoiEXLab Absolutely.  However, item (5) gives me peace of mind that I'm not accidentally overwriting production changes that were not pushed to Git. :smile:

**Comment by RoiEXLab** [comment]
@ssoloff Would you mind removing the wikipage/the complete wiki if possible?

**Comment by ssoloff** [comment]
The page has been removed, but I don't think I have permission to disable the wiki feature.

**Comment by RoiEXLab** [comment]
@ron-murhammer Would you be so kind to remove the wiki feature?
See the discussion above for more information

**Comment by ron-murhammer** [comment]
Done.

**Comment by RoiEXLab** [comment]
Thanks

**Pull request merged**
